stages:
  - pre-build
  - pre-check
  - build
  - test
  - publish
  - notify


#
# PRE-BUILD
#

pre_build_next:
  stage: pre-build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - export OLDVERSION=$(npm view @ubud-app/server@next version)
    - jq -M ".version=\"$OLDVERSION\"" package.json|sponge package.json
    - npm --no-git-tag-version version prerelease
    - cp package.json package.new.json
    - docker pull node:slim
    - docker build --no-cache
        --build-arg NODE_ENV="develop"
        --build-arg CLIENT_TAG="next"
        --build-arg NEXT="1"
        -t "docker.sebbo.net/ubud/server:${CI_COMMIT_SHA}" .
    - docker push "docker.sebbo.net/ubud/server:${CI_COMMIT_SHA}"
  artifacts:
    paths:
      - package.new.json
    expire_in: 2 weeks
  except:
    - tags


#
# PRE-CHECK
#

check_lint:
  stage: pre-check
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker pull "docker.sebbo.net/ubud/server:${CI_COMMIT_SHA}"
    - docker run --rm "docker.sebbo.net/ubud/server:${CI_COMMIT_SHA}" npm run check
  except:
    - tags


#
# BUILD
#

build_next:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - rm -f ./package.json
    - mv ./package.new.json ./package.json
    - docker pull node:slim
    - docker build --no-cache
      --build-arg NODE_ENV="production"
      --build-arg CLIENT_TAG="next"
      --build-arg NEXT="1"
      -t "ubud/server:${CI_COMMIT_SHA}-next" .
    - docker push "ubud/server:${CI_COMMIT_SHA}-next"
  only:
    - develop

build:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - rm -f ./package.json
    - mv ./package.new.json ./package.json
    - docker pull node:slim
    - docker build --no-cache
      --build-arg NODE_ENV="production"
      -t "ubud/server:${CI_COMMIT_SHA}" .
    - docker push "ubud/server:${CI_COMMIT_SHA}"
  only:
    - tags

build_next_arm32v7:
  stage: build
  tags:
    - docker-host
    - arm
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - rm -f ./package.json
    - mv ./package.new.json ./package.json
    - docker system prune -f
    - docker pull arm32v7/node:slim
    - docker build --no-cache
      --build-arg BASEIMAGE="arm32v7/node:slim"
      --build-arg NODE_ENV="production"
      --build-arg CLIENT_TAG="next"
      --build-arg NEXT="1"
      -t "ubud/server:${CI_COMMIT_SHA}-next-arm32v7" .
    - docker push "ubud/server:${CI_COMMIT_SHA}-next-arm32v7"
  only:
    - develop

build_arm32v7:
  stage: build
  tags:
    - docker-host
    - arm
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - rm -f ./package.json
    - mv ./package.new.json ./package.json
    - docker system prune -f
    - docker pull arm32v7/node:slim
    - docker build --no-cache
      --build-arg BASEIMAGE="arm32v7/node:slim"
      --build-arg NODE_ENV="production"
      -t "ubud/server:${CI_COMMIT_SHA}-arm32v7" .
    - docker push "ubud/server:${CI_COMMIT_SHA}-arm32v7"
  only:
    - tags


#
# PUBLISH
#

publish_github_branch:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  retry: 2
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git push "https://${GITHUB_AUTH}@github.com/ubud-app/server.git" --all
  only:
    - master
    - develop

publish_github_tag:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  retry: 2
  script:
    - git push "https://${GITHUB_AUTH}@github.com/ubud-app/server.git" --tags
  only:
    - tags

publish_npm_next:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - yarn install
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - rm -f ./package.json
    - mv ./package.new.json ./package.json
    - npm publish --tag "next" --access public
  only:
    - develop

publish_npm:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - yarn install
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - rm -f ./package.json
    - mv ./package.new.json ./package.json
    - npm publish --access public
  only:
    - tags

publish_docker_next:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker manifest create "ubud/server:next" "ubud/server:${CI_COMMIT_SHA}-next" "ubud/server:${CI_COMMIT_SHA}-next-arm32v7"
    - docker manifest annotate --arch "amd64" --os "linux" "ubud/server:next" "ubud/server:${CI_COMMIT_SHA}-next"
    - docker manifest annotate --arch "arm" --os "linux" "ubud/server:next" "ubud/server:${CI_COMMIT_SHA}-next-arm32v7"
    - docker manifest push -p "ubud/server:next"
  only:
    - develop

publish_docker:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker manifest create "ubud/server" "ubud/server:${CI_COMMIT_SHA}" "ubud/server:${CI_COMMIT_SHA}-arm32v7"
    - docker manifest annotate --arch "amd64" --os "linux" "ubud/server" "ubud/server:${CI_COMMIT_SHA}"
    - docker manifest annotate --arch "arm" --os "linux" "ubud/server" "ubud/server:${CI_COMMIT_SHA}-arm32v7"
    - docker manifest push -p "ubud/server"
  only:
    - tags

publish_docker_version:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - export VERSION=$(cat ./package.new.json | jq -rM .version)
    - docker manifest create "ubud/server:${VERSION}" "ubud/server:${CI_COMMIT_SHA}" "ubud/server:${CI_COMMIT_SHA}-arm32v7"
    - docker manifest annotate --arch "amd64" --os "linux" "ubud/server:${VERSION}" "ubud/server:${CI_COMMIT_SHA}"
    - docker manifest annotate --arch "arm" --os "linux" "ubud/server:${VERSION}" "ubud/server:${CI_COMMIT_SHA}-arm32v7"
    - docker manifest push -p "ubud/server:${VERSION}"
  only:
    - tags

private-deployment:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  environment:
    name: ubud.sebbo.net
    url: https://ubud.sebbo.net/
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker pull "ubud/server:${CI_COMMIT_SHA}-next"
    - docker stop "ubud" || true
    - docker rm "ubud" || true
    - docker create --restart "always" --name="ubud"
        --link mariadb:db
        -v "/etc/timezone:/etc/timezone:ro" -v "/etc/localtime:/etc/localtime:ro"
        -e "DATABASE=${DEPLOYMENT_DATABASE}"
        -p 127.0.0.1:10060:8080
        "ubud/server:${CI_COMMIT_SHA}-next"
    - docker start ubud
  only:
    - develop


#
# NOTIFY
#

notify:
  stage: notify
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - curl -X "POST" "https://beacon.ubud.club/webhooks/update-components/${NOTIFY_WEBHOOK_SECRET}"
  only:
    - develop
    - tags
