name: Release
on:
  push:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set version
        run: |
          export OLDVERSION=$(npm view @ubud-app/server@next version)
          jq -M ".version=\"$OLDVERSION\"" package.json > package.new.json
          rm -f package.json
          mv package.new.json package.json
      - name: pull dependencies
        run: |
          docker pull multiarch/qemu-user-static:register
          docker pull multiarch/alpine:x86_64-latest-stable
      - name: register quemu user static
        run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - name: build test docker container
        run: |
          docker build \
              --build-arg BASEIMAGE="multiarch/alpine:x86_64-latest-stable" \
              --build-arg NODE_ENV="develop" \
              --build-arg CLIENT_TAG="next" \
              --build-arg NEXT="1" \
              -t "ubud-server-tests:${GITHUB_SHA}" .
      - name: run checks
        run: docker run --rm "ubud-server-tests:${GITHUB_SHA}" npm run check


  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: docker login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ubud-app --password-stdin docker.pkg.github.com
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: install semantic-release
        run: npm ci
      - name: semantic-release
        run: npx semantic-release
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ubud
          SENTRY_PROJECT: server
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          NOTIFY_WEBHOOK_SECRET: ${{ secrets.NOTIFY_WEBHOOK_SECRET }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
